Metrics/MethodLength:
  Max: 45

Metrics/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 165

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/AbcSize:
  Max: 40


Metrics/PerceivedComplexity:
  Max: 15

Style/RaiseArgs:
  EnforcedStyle: compact
